export const INITIAL_DEPARTMENTS = [
  {
    id: 'dept-1',
    name: 'Engineering',
    description: 'Software development, cloud infrastructure, AI engineering, and quality assurance.',
    manager_id: 'emp-1',
    budget: 850000,
    color: '#3b82f6', // blue
  },
  {
    id: 'dept-2',
    name: 'Product & Design',
    description: 'Product strategy, UI/UX architecture, design systems, and user research.',
    manager_id: 'emp-4',
    budget: 420000,
    color: '#8b5cf6', // purple
  },
  {
    id: 'dept-3',
    name: 'Marketing & Brand',
    description: 'Global brand awareness, growth marketing, content strategy, and public relations.',
    manager_id: 'emp-7',
    budget: 310000,
    color: '#ec4899', // pink
  },
  {
    id: 'dept-4',
    name: 'Sales & Revenue',
    description: 'Enterprise accounts, customer acquisitions, SDR, and partnerships.',
    manager_id: 'emp-10',
    budget: 540000,
    color: '#10b981', // emerald
  },
  {
    id: 'dept-5',
    name: 'People & Culture',
    description: 'Talent acquisition, employee experience, benefits administration, and HR compliance.',
    manager_id: 'emp-13',
    budget: 280000,
    color: '#f59e0b', // amber
  },
  {
    id: 'dept-6',
    name: 'Finance & Legal',
    description: 'Financial planning, corporate accounting, legal compliance, and tax operations.',
    manager_id: 'emp-16',
    budget: 360000,
    color: '#6366f1', // indigo
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-1',
    first_name: 'Marcus',
    last_name: 'Vance',
    email: 'marcus.vance@pulsehr.io',
    phone: '+1 (555) 234-5678',
    role: 'VP of Engineering',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 195000,
    join_date: '2022-03-15',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Distributed systems architect with 15+ years experience building hyper-scale microservices.',
    emergency_contact_name: 'Elena Vance (Spouse)',
    emergency_contact_phone: '+1 (555) 891-2345',
    created_at: '2022-03-15T09:00:00Z',
  },
  {
    id: 'emp-2',
    first_name: 'Sarah',
    last_name: 'Chen',
    email: 'sarah.chen@pulsehr.io',
    phone: '+1 (555) 345-6789',
    role: 'Lead Full-Stack Engineer',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 165000,
    join_date: '2023-01-10',
    manager_id: 'emp-1',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=256&h=256&fit=crop&crop=faces',
    location: 'Seattle, WA',
    bio: 'Passionate about React 19, TypeScript, Next.js, and clean software architecture.',
    emergency_contact_name: 'David Chen (Brother)',
    emergency_contact_phone: '+1 (555) 902-3456',
    created_at: '2023-01-10T09:00:00Z',
  },
  {
    id: 'emp-3',
    first_name: 'Devon',
    last_name: 'Reynolds',
    email: 'devon.reynolds@pulsehr.io',
    phone: '+1 (555) 456-7890',
    role: 'Senior DevOps / SRE Engineer',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Remote',
    salary: 155000,
    join_date: '2023-06-01',
    manager_id: 'emp-1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&h=256&fit=crop&crop=faces',
    location: 'Austin, TX (Remote)',
    bio: 'Kubernetes wizard, Terraform fanatic, and advocate for 99.999% system uptime.',
    emergency_contact_name: 'Chloe Reynolds (Sister)',
    emergency_contact_phone: '+1 (555) 123-9876',
    created_at: '2023-06-01T09:00:00Z',
  },
  {
    id: 'emp-4',
    first_name: 'Amara',
    last_name: 'Okafor',
    email: 'amara.okafor@pulsehr.io',
    phone: '+1 (555) 567-8901',
    role: 'Head of Product Design',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 175000,
    join_date: '2022-07-20',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Champion of human-centered enterprise workflows, accessibility, and micro-interactions.',
    emergency_contact_name: 'Nnamdi Okafor (Father)',
    emergency_contact_phone: '+1 (555) 234-8765',
    created_at: '2022-07-20T09:00:00Z',
  },
  {
    id: 'emp-5',
    first_name: 'Liam',
    last_name: 'Gallagher',
    email: 'liam.gallagher@pulsehr.io',
    phone: '+1 (555) 678-9012',
    role: 'Principal UX Researcher',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 140000,
    join_date: '2023-04-12',
    manager_id: 'emp-4',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=256&h=256&fit=crop&crop=faces',
    location: 'London, UK',
    bio: 'Conducts deep customer interviews, ethnographic usability studies, and UX benchmarking.',
    emergency_contact_name: 'Fiona Gallagher (Spouse)',
    emergency_contact_phone: '+44 20 7946 0912',
    created_at: '2023-04-12T09:00:00Z',
  },
  {
    id: 'emp-6',
    first_name: 'Chloe',
    last_name: 'Dubois',
    email: 'chloe.dubois@pulsehr.io',
    phone: '+1 (555) 789-0123',
    role: 'Senior Product Designer',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'On Leave',
    salary: 135000,
    join_date: '2024-02-01',
    manager_id: 'emp-4',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=256&h=256&fit=crop&crop=faces',
    location: 'Paris / Remote',
    bio: 'Design system lead creating frictionless component libraries and fluid animation states.',
    emergency_contact_name: 'Antoine Dubois (Partner)',
    emergency_contact_phone: '+33 6 12 34 56 78',
    created_at: '2024-02-01T09:00:00Z',
  },
  {
    id: 'emp-7',
    first_name: 'Maya',
    last_name: 'Lin',
    email: 'maya.lin@pulsehr.io',
    phone: '+1 (555) 890-1234',
    role: 'Director of Growth Marketing',
    department_id: 'dept-3',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 160000,
    join_date: '2022-11-15',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=256&h=256&fit=crop&crop=faces',
    location: 'New York, NY',
    bio: 'Performance marketing leader obsessed with CAC/LTV payback, SEO dominance, and viral product loops.',
    emergency_contact_name: 'James Lin (Brother)',
    emergency_contact_phone: '+1 (555) 345-9876',
    created_at: '2022-11-15T09:00:00Z',
  },
  {
    id: 'emp-8',
    first_name: 'Lucas',
    last_name: 'Moretti',
    email: 'lucas.moretti@pulsehr.io',
    phone: '+1 (555) 901-2345',
    role: 'Content & Social Strategist',
    department_id: 'dept-3',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 95000,
    join_date: '2024-05-20',
    manager_id: 'emp-7',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=256&h=256&fit=crop&crop=faces',
    location: 'New York, NY',
    bio: 'Crafting compelling tech stories, industry whitepapers, and viral social media campaigns.',
    emergency_contact_name: 'Sofia Moretti (Mother)',
    emergency_contact_phone: '+1 (555) 456-1234',
    created_at: '2024-05-20T09:00:00Z',
  },
  {
    id: 'emp-9',
    first_name: 'Zoe',
    last_name: 'Kowalski',
    email: 'zoe.kowalski@pulsehr.io',
    phone: '+1 (555) 012-3456',
    role: 'Brand Designer & Visual Producer',
    department_id: 'dept-3',
    employment_type: 'Contract',
    status: 'Remote',
    salary: 88000,
    join_date: '2025-01-15',
    manager_id: 'emp-7',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=256&h=256&fit=crop&crop=faces',
    location: 'Berlin, Germany',
    bio: '3D motion artist and visual branding consultant crafting iconic brand visuals.',
    emergency_contact_name: 'Jan Kowalski (Father)',
    emergency_contact_phone: '+49 30 123456',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'emp-10',
    first_name: 'Tariq',
    last_name: 'Al-Mansoor',
    email: 'tariq.mansoor@pulsehr.io',
    phone: '+1 (555) 123-7890',
    role: 'VP of Enterprise Sales',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 190000,
    join_date: '2022-05-01',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=256&h=256&fit=crop&crop=faces',
    location: 'Chicago, IL',
    bio: 'Over 12 years exceeding Fortune 500 SaaS quotas and managing high-velocity enterprise deal cycles.',
    emergency_contact_name: 'Fatima Al-Mansoor (Spouse)',
    emergency_contact_phone: '+1 (555) 567-2345',
    created_at: '2022-05-01T09:00:00Z',
  },
  {
    id: 'emp-11',
    first_name: 'Jessica',
    last_name: 'Taylor',
    email: 'jessica.taylor@pulsehr.io',
    phone: '+1 (555) 234-8901',
    role: 'Enterprise Account Executive',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 130000,
    join_date: '2023-08-14',
    manager_id: 'emp-10',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a171edd2521e?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Closing high ACV contracts and partnering with CTOs & Chief People Officers.',
    emergency_contact_name: 'Robert Taylor (Father)',
    emergency_contact_phone: '+1 (555) 678-3456',
    created_at: '2023-08-14T09:00:00Z',
  },
  {
    id: 'emp-12',
    first_name: 'Carlos',
    last_name: 'Santana',
    email: 'carlos.santana@pulsehr.io',
    phone: '+1 (555) 345-9012',
    role: 'Senior Sales Engineer',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 145000,
    join_date: '2024-01-08',
    manager_id: 'emp-10',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=256&h=256&fit=crop&crop=faces',
    location: 'Miami, FL',
    bio: 'Bridges technical depth and sales solutions for enterprise security and API integrations.',
    emergency_contact_name: 'Maria Santana (Mother)',
    emergency_contact_phone: '+1 (555) 789-4567',
    created_at: '2024-01-08T09:00:00Z',
  },
  {
    id: 'emp-13',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena.rostova@pulsehr.io',
    phone: '+1 (555) 456-0123',
    role: 'Chief People Officer',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 200000,
    join_date: '2021-10-01',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Dedicated to cultivating an inspiring, inclusive, and world-class work environment for every team member.',
    emergency_contact_name: 'Viktor Rostov (Spouse)',
    emergency_contact_phone: '+1 (555) 890-5678',
    created_at: '2021-10-01T09:00:00Z',
  },
  {
    id: 'emp-14',
    first_name: 'Jordan',
    last_name: 'Miller',
    email: 'jordan.miller@pulsehr.io',
    phone: '+1 (555) 567-1234',
    role: 'Senior Technical Recruiter',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 110000,
    join_date: '2023-03-20',
    manager_id: 'emp-13',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=256&h=256&fit=crop&crop=faces',
    location: 'Denver, CO (Remote)',
    bio: 'Headhunting top-tier AI researchers, senior backend wizards, and engineering leads.',
    emergency_contact_name: 'Ashley Miller (Spouse)',
    emergency_contact_phone: '+1 (555) 901-6789',
    created_at: '2023-03-20T09:00:00Z',
  },
  {
    id: 'emp-15',
    first_name: 'Rachel',
    last_name: 'Greenberg',
    email: 'rachel.greenberg@pulsehr.io',
    phone: '+1 (555) 678-2345',
    role: 'People Operations & Culture Lead',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 105000,
    join_date: '2024-03-10',
    manager_id: 'emp-13',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Oversees onboarding rituals, DEI initiatives, perks, and wellness retreats.',
    emergency_contact_name: 'Samuel Greenberg (Brother)',
    emergency_contact_phone: '+1 (555) 012-7890',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'emp-16',
    first_name: 'Nathan',
    last_name: 'Cross',
    email: 'nathan.cross@pulsehr.io',
    phone: '+1 (555) 789-3456',
    role: 'Head of Finance & Operations',
    department_id: 'dept-6',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 185000,
    join_date: '2022-01-15',
    manager_id: null,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=256&h=256&fit=crop&crop=faces',
    location: 'New York, NY',
    bio: 'CPA and strategic finance officer guiding capital allocation, runway planning, and corporate compliance.',
    emergency_contact_name: 'Karen Cross (Spouse)',
    emergency_contact_phone: '+1 (555) 123-8901',
    created_at: '2022-01-15T09:00:00Z',
  },
  {
    id: 'emp-17',
    first_name: 'Priya',
    last_name: 'Patel',
    email: 'priya.patel@pulsehr.io',
    phone: '+1 (555) 890-4567',
    role: 'Senior Financial Analyst',
    department_id: 'dept-6',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 125000,
    join_date: '2023-09-01',
    manager_id: 'emp-16',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=256&h=256&fit=crop&crop=faces',
    location: 'New York, NY',
    bio: 'Builds financial forecasting models, cash flow forecasts, and payroll ledger audits.',
    emergency_contact_name: 'Rohan Patel (Father)',
    emergency_contact_phone: '+1 (555) 234-9012',
    created_at: '2023-09-01T09:00:00Z',
  },
  {
    id: 'emp-18',
    first_name: 'Alex',
    last_name: 'Rivera',
    email: 'alex.rivera@pulsehr.io',
    phone: '+1 (555) 901-5678',
    role: 'Frontend Software Engineer',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 120000,
    join_date: '2025-06-15',
    manager_id: 'emp-2',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=256&h=256&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    bio: 'Crafting responsive UI, data visualisations, and web accessibility features.',
    emergency_contact_name: 'Lucia Rivera (Sister)',
    emergency_contact_phone: '+1 (555) 345-0123',
    created_at: '2025-06-15T09:00:00Z',
  },
];

export const INITIAL_JOB_POSTINGS = [
  {
    id: 'job-1',
    title: 'Staff AI Infrastructure Engineer',
    department_id: 'dept-1',
    location: 'San Francisco, CA (Hybrid)',
    type: 'Full-Time',
    experience_level: 'Staff / 8+ Years',
    salary_range: '$200k - $240k + Equity',
    description: 'Lead the design and scale of our multi-modal generative inference platform, GPU clusters, and real-time streaming pipeline.',
    requirements: 'Deep experience with PyTorch, CUDA kernel optimizations, Kubernetes, gRPC, and high-throughput low-latency distributed systems.',
    status: 'Active',
    posted_date: '2026-08-25',
    applicants_count: 34,
  },
  {
    id: 'job-2',
    title: 'Senior Product Designer (Design Systems)',
    department_id: 'dept-2',
    location: 'Remote (US / Europe)',
    type: 'Full-Time',
    experience_level: 'Senior / 5+ Years',
    salary_range: '$140k - $175k',
    description: 'Own our multi-platform enterprise design system, token architecture, Figma component ecosystem, and accessibility audit guidelines.',
    requirements: 'Strong portfolio demonstrating production design systems, Figma tokens, code-aligned components, and WCAG AAA compliance.',
    status: 'Active',
    posted_date: '2026-09-01',
    applicants_count: 52,
  },
  {
    id: 'job-3',
    title: 'Enterprise Account Executive (FinTech & Tech)',
    department_id: 'dept-4',
    location: 'New York, NY',
    type: 'Full-Time',
    experience_level: 'Mid-Senior / 4+ Years',
    salary_range: '$130k Base / $260k OTE',
    description: 'Drive high-value enterprise sales cycles, negotiate six-figure SaaS contracts with Chief People Officers and CIOs.',
    requirements: 'Proven track record of quota attainment in B2B SaaS, exceptional consultative selling skills, and MEDDPICC mastery.',
    status: 'Active',
    posted_date: '2026-09-05',
    applicants_count: 28,
  },
  {
    id: 'job-4',
    title: 'Senior Developer Relations & Technical Writer',
    department_id: 'dept-3',
    location: 'Remote',
    type: 'Full-Time',
    experience_level: 'Senior / 4+ Years',
    salary_range: '$120k - $150k',
    description: 'Engage developer communities, craft world-class documentation, create interactive sandboxes, and speak at premier tech summits.',
    requirements: 'Software engineering background with proven writing or public speaking track record, familiarity with Next.js and API design.',
    status: 'Active',
    posted_date: '2026-09-10',
    applicants_count: 19,
  },
];

export const INITIAL_CANDIDATES = [
  {
    id: 'cand-1',
    job_id: 'job-1',
    name: 'Dmitri Voronov',
    email: 'dmitri.v@example.com',
    phone: '+1 (555) 771-8899',
    stage: 'Offer',
    rating: 5,
    applied_date: '2026-08-28',
    notes: 'Incredible technical interview. Built custom CUDA distributed caching layer in under 45 minutes.',
  },
  {
    id: 'cand-2',
    job_id: 'job-1',
    name: 'Kavita Subramaniam',
    email: 'kavita.sub@example.com',
    phone: '+1 (555) 662-7788',
    stage: 'Interview',
    rating: 4,
    applied_date: '2026-09-02',
    notes: 'Strong distributed systems background at AWS. Architecture round scheduled with Marcus Vance.',
  },
  {
    id: 'cand-3',
    job_id: 'job-2',
    name: 'Oliver Thorne',
    email: 'oliver.t@example.com',
    phone: '+1 (555) 553-6677',
    stage: 'Interview',
    rating: 5,
    applied_date: '2026-09-04',
    notes: 'Portfolio is phenomenal. Beautiful attention to micro-interactions and dark mode token contrast.',
  },
  {
    id: 'cand-4',
    job_id: 'job-2',
    name: 'Claire Beauchamp',
    email: 'claire.b@example.com',
    phone: '+1 (555) 444-5566',
    stage: 'Screening',
    rating: 4,
    applied_date: '2026-09-12',
    notes: 'Great background at Stripe. Recruiter screening passed; coordinating review with Amara.',
  },
  {
    id: 'cand-5',
    job_id: 'job-3',
    name: 'Marcus Sterling',
    email: 'm.sterling@example.com',
    phone: '+1 (555) 333-4455',
    stage: 'Applied',
    rating: 3,
    applied_date: '2026-09-18',
    notes: 'Resume under review. Top performer at Snowflake with $2.4M closed quota.',
  },
  {
    id: 'cand-6',
    job_id: 'job-4',
    name: 'Aisha Al-Hassan',
    email: 'aisha.dev@example.com',
    phone: '+1 (555) 222-3344',
    stage: 'Screening',
    rating: 4,
    applied_date: '2026-09-14',
    notes: 'Created popular open-source Next.js tutorial series with 100k+ YouTube views.',
  },
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    id: 'ann-1',
    title: '🌿 Annual Wellness Week & Mental Health Days Announced',
    content: 'All team members receive 2 additional wellness floating holidays for Q4 2026. Take time to recharge and focus on mental well-being!',
    author_id: 'emp-13',
    category: 'Celebration',
    pinned: 1,
    created_at: '2026-09-18T10:00:00Z',
  },
  {
    id: 'ann-2',
    title: '🚀 Q3 All-Hands & Product Keynote - September 28th',
    content: 'Join us live or on stream as we unveil PulseHR 3.0 features, celebrate promotions, and outline our 2027 enterprise roadmap.',
    author_id: 'emp-1',
    category: 'General',
    pinned: 1,
    created_at: '2026-09-15T14:30:00Z',
  },
  {
    id: 'ann-3',
    title: '💼 2027 Open Enrollment & Updated Health Benefits Guide',
    content: 'Review the new comprehensive 401(k) matching tiers (now up to 6% dollar-for-dollar) and enhanced dental/vision coverage in the benefits portal.',
    author_id: 'emp-15',
    category: 'Policy',
    pinned: 0,
    created_at: '2026-09-10T11:00:00Z',
  },
];

export const INITIAL_PERFORMANCE_REVIEWS = [
  {
    id: 'rev-1',
    employee_id: 'emp-2',
    reviewer_id: 'emp-1',
    review_period: 'Mid-Year 2026',
    rating: 4.9,
    goals_achievement: 98,
    strengths: 'Exceptional architectural foresight, mentorship of junior engineers, and delivery of zero-downtime database migrations.',
    areas_for_growth: 'Continue expanding public tech writing and representing PulseHR at engineering conferences.',
    status: 'Completed',
    created_at: '2026-07-15T12:00:00Z',
  },
  {
    id: 'rev-2',
    employee_id: 'emp-18',
    reviewer_id: 'emp-2',
    review_period: 'Q2 2026',
    rating: 4.6,
    goals_achievement: 94,
    strengths: 'Fast learning curve, attention to detail in UI implementation, and proactive code reviews.',
    areas_for_growth: 'Take ownership of complete end-to-end fullstack features from backend schema to frontend polish.',
    status: 'Completed',
    created_at: '2026-07-20T14:00:00Z',
  },
  {
    id: 'rev-3',
    employee_id: 'emp-5',
    reviewer_id: 'emp-4',
    review_period: 'Mid-Year 2026',
    rating: 4.8,
    goals_achievement: 96,
    strengths: 'Translates complex qualitative feedback into actionable user journey maps. Outstanding cross-functional collaboration.',
    areas_for_growth: 'Standardize the customer interview repository for faster discovery across engineering pods.',
    status: 'Completed',
    created_at: '2026-07-18T10:00:00Z',
  },
];
